config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :livros
    end
  end

  resources :livros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/livro.rb
class Livro < ApplicationRecord
end

app/controllers/api/v1/livros_controller.rb
class LivrosController < ApplicationController
  def index
    @livros = Livro.all
  end

  def show
    @livro = Livro.find(params[:id])
  end

  def new
    @livro = Livro.new
  end

  def create
    @livro = Livro.new(livro_params)
    if @livro.save
      redirect_to @livro, notice: 'Livro foi criado com sucesso.'
    else
      render :new
    end
  end

  def edit
    @livro = Livro.find(params[:id])
  end

  def update
    @livro = Livro.find(params[:id])
    if @livro.update(livro_params)
      redirect_to @livro, notice: 'Livro foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @livro = Livro.find(params[:id])
    @livro.destroy
    redirect_to livros_url, notice: 'Livro foi excluído com sucesso.'
  end

  private

  def livro_params
    params.require(:livro).permit(:nome, :autor, :preco, :ativo, :data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
    def index
      @livros = Livro.all
    end
  
    def show
      @livro = Livro.find(params[:id])
    end
  
    def new
      @livro = Livro.new
    end
  
    def create
      @livro = Livro.new(livro_params)
      if @livro.save
        redirect_to @livro, notice: 'Livro foi criado com sucesso.'
      else
        render :new
      end
    end
  
    def edit
      @livro = Livro.find(params[:id])
    end
  
    def update
      @livro = Livro.find(params[:id])
      if @livro.update(livro_params)
        redirect_to @livro, notice: 'Livro foi atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @livro = Livro.find(params[:id])
      @livro.destroy
      redirect_to livros_url, notice: 'Livro foi excluído com sucesso.'
    end
  
    private
  
    def livro_params
      params.require(:livro).permit(:nome, :autor, :preco, :ativo, :data)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BibliotecaApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro, local: true) do |form| %>
    <% if livro.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(livro.errors.count, "error") %> proibiu este livro de ser salvo:</h2>
  
        <ul>
          <% livro.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :nome %>
      <%= form.text_field :nome %>
    </div>
  
    <div class="field">
      <%= form.label :autor %>
      <%= form.text_field :autor %>
    </div>
  
    <div class="field">
      <%= form.label :preco %>
      <%= form.text_field :preco %>
    </div>
  
    <div class="field">
      <%= form.label :ativo %>
      <%= form.check_box :ativo %>
    </div>
  
    <div class="field">
      <%= form.label :data %>
      <%= form.datetime_select :data %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/livros/edit.html.erb
<h1>Editar Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Voltar', livros_path %>

app/views/livros/index.html.erb
<h1>Lista de Livros</h1>

<%= link_to 'Novo Livro', new_livro_path %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Autor</th>
      <th>Preço</th>
      <th>Ativo</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.nome %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.preco %></td>
        <td><%= livro.ativo %></td>
        <td><%= livro.data %></td>
        <td><%= link_to 'Mostrar', livro %></td>
        <td><%= link_to 'Editar', edit_livro_path(livro) %></td>
        <td><%= link_to 'Excluir', livro, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/livros/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Voltar', livros_path %>

app/views/livros/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @livro.nome %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @livro.preco %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= @livro.ativo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @livro.data %>
</p>

<%= link_to 'Editar', edit_livro_path(@livro) %> |
<%= link_to 'Voltar', livros_path %>